### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Cha14ka** [BladeMight/cusi#1]
![изображение](https://user-images.githubusercontent.com/16352397/76687677-4b40e500-6637-11ea-9876-952b6143d53a.png)

**Comment by BladeMight** [comment]
As the browser does for that video:
![2020 03 15 - 05'20'57_rect](https://user-images.githubusercontent.com/11931888/76694555-dabcb700-667c-11ea-8d6d-c10efd6ac195.jpg)
I think this video is not available.
Tried some other video, works:


```sh
$ cusi 'https://video.sibnet.ru/video3870485' '#echo'
https://dv98.sibnet.ru/35/53/30/3553300.mp4?st=HoCKrP00ZacZyiZNJnEwRg&e=1584272000&stor=48&noip=1&cache=30
Самые невероятные заброшенные машины.mp4
```
