### ISSUE TITLE
sibnet does not give direct url

### ISSUE THREAD

**Issue by Mryuksel101** [BladeMight/cusi#4]
![Ekran Görüntüsü (906)](https://user-images.githubusercontent.com/99680265/215505900-f658b64c-a77f-47bc-9b0a-d98407a20865.png)

Sibnet does not give direct url. What can i do

**Comment by BladeMight** [comment]
Default action is - do nothing, your echo isn't correct it actually needs to be with a `#`:

```bash
./cusi https://video.sibnet.ru/video3870485/ \#echo
https://dv98.sibnet.ru/35/53/30/3553300.mp4?st=7Iiv3QZFRnsj1pjWwCQy5g&e=1675120000&stor=51&noip=1
Самые невероятные заброшенные машины.mp4
```

**Comment by Mryuksel101** [comment]
I'm trying to get a direct link by doing shell_exec with PHP, but it doesn't work. How can I run this in a server environment?

**Comment by BladeMight** [comment]
> PHP

Why not use the already existing [cusi.php](https://github.com/BladeMight/cusi/blob/master/cusi.php) then? You can see how it works inside.
